apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mern-app
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://idesta705_db_user:Eo3KmVVfOrP8eHHs@cluster0.jrcgqcy.mongodb.net/products?appName=Cluster0




  docker run -d \
  --name product_store_backend \
  -e MONGO_URI="mongodb+srv://<username>:<password>@<cluster-info>.mongodb.net/<database-name>?retryWrites=true&w=majority" \
  -p 5000:5000 \
  prd_str_cicd_backend_fixed