[masters]
master ansible_host=196.188.250.157 ansible_port=2201 ansible_user=root ansible_ssh_private_key_file=/home/zergaw/Documents/Github/product_store/cloudstack_keypair

[workers]
worker-0 ansible_host=196.188.250.157 ansible_port=2205 ansible_user=root ansible_ssh_private_key_file=/home/zergaw/Documents/Github/product_store/cloudstack_keypair
worker-1 ansible_host=196.188.250.157 ansible_port=2206 ansible_user=root ansible_ssh_private_key_file=/home/zergaw/Documents/Github/product_store/cloudstack_keypair

[k8s:children]
masters
workers

[all:vars]
# Disables host key checking to prevent the "authenticity can't be established" prompt
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
