apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. First, create the environment (Namespace)
resources:
  - namespaces/app-namespace.yaml
  - secrets/mongo-secret.yaml
  - backend/backend-deployment.yaml
  - backend/backend-service.yaml
  - frontend/frontend-deployment.yaml
  - frontend/frontend-service.yaml
  - ingress/app-ingress.yaml

# 2. Common Metadata (Adds these to EVERY resource above)
commonLabels:
  project: product-store
  tier: mern-stack

# 3. Namespace Override (Safety net)
# This ensures every resource is forced into your mern-app namespace
namespace: mern-app
