---
- name: Prepare All Nodes
  hosts: k8s
  become: true
  tasks:
    - name: Update and install dependencies
      apt:
        {
          name: [curl, apt-transport-https, ca-certificates, gnupg],
          state: present,
          update_cache: yes,
        }

    - name: Disable Swap
      shell: "swapoff -a && sed -i '/ swap / s/^/#/' /etc/fstab"

    - name: Load Kernel Modules immediately
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Ensure modules load on boot
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Apply Sysctl params (Bridge Networking)
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        sysctl_file: /etc/sysctl.d/k8s.conf
        reload: yes
      with_items:
        - { key: "net.bridge.bridge-nf-call-iptables", value: "1" }
        - { key: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
        - { key: "net.ipv4.ip_forward", value: "1" }

    - name: Apply Sysctl
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
      notify: Reload Sysctl

    - name: Install Containerd
      apt: { name: containerd, state: present }

    - name: Configure Containerd (SystemdCgroup)
      shell: |
        mkdir -p /etc/containerd
        containerd config default | tee /etc/containerd/config.toml > /dev/null
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
      notify: Restart Containerd

  handlers:
    - name: Reload Sysctl
      command: sysctl --system
    - name: Restart Containerd
      systemd: { name: containerd, state: restarted }
