---
- name: Install Flannel CNI
  hosts: masters
  become: true
  vars:
    kubeconfig_path: "/etc/kubernetes/admin.conf"
    network_interface: "ens3"

  tasks:
    - name: 1. Prepare Flannel Manifest
      get_url:
        url: https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
        dest: /tmp/kube-flannel.yml

    - name: 2. Configure Interface and MTU
      replace:
        path: /tmp/kube-flannel.yml
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
        - {
            regexp: "(?m)- --kube-subnet-mgr$",
            replace: "- --kube-subnet-mgr\n        - --iface={{ network_interface }}",
          }
        - {
            regexp: '\"Network\": \"10.244.0.0/16\"',
            replace: '"Network": "10.244.0.0/16", "Backend": { "Type": "vxlan", "MTU": 1400 }',
          }

    - name: 3. Apply Flannel (with force to avoid immutable field errors)
      command: kubectl apply -f /tmp/kube-flannel.yml --force
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: 4. Fix CoreDNS Loop
      shell: |
        kubectl -n kube-system get configmap coredns -o yaml | \
        sed 's/forward . \/etc\/resolv.conf/forward . 8.8.8.8 1.1.1.1/g' | \
        kubectl apply -f -
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      ignore_errors: true

    - name: 5. Restart CoreDNS
      shell: "kubectl rollout restart -n kube-system deployment coredns"
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: 6. Wait for ALL Nodes to be Ready
      shell: "kubectl get nodes --no-headers | grep -v ' Ready' | wc -l"
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: not_ready_count
      until: not_ready_count.stdout == "0"
      retries: 20
      delay: 15
      changed_when: false

    - name: 7. Show Cluster Status
      command: kubectl get nodes -o wide
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      register: final_status

    - name: Display Status
      debug:
        var: final_status.stdout_lines
