---
- name: Setup Master
  hosts: masters
  become: true
  tasks:
    - name: Add K8s Repo & Install Tools
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /" > /etc/apt/sources.list.d/kubernetes.list

    - apt:
        { name: [kubelet, kubeadm, kubectl], state: present, update_cache: yes }

    - name: Kubeadm Init
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      args: { creates: /etc/kubernetes/admin.conf }

    - name: Generate Join Token
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Share Join Token
      set_fact:
        k8s_join_cmd: "{{ join_command.stdout }}"
      delegate_to: "{{ item }}"
      with_items: "{{ groups['workers'] }}"

    - name: Setup Kubeconfig
      become_user: ubuntu
      shell: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config
