# ../ansible/playbooks/site.yml
---
- import_playbook: base.yml # OS Prep (Swap, Containerd, Python)
- import_playbook: master.yml # Init Master & Create Join Token
- import_playbook: cni.yml # Install Flannel Networking
- import_playbook: worker.yml # Install Tools & Join Workers
