---
- name: Join Workers
  hosts: workers
  become: true
  tasks:
    - name: 1. Add K8s Repo & Install Tools
      shell: |
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -y -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /" > /etc/apt/sources.list.d/kubernetes.list
      args:
        creates: /etc/apt/sources.list.d/kubernetes.list

    - name: 2. Install K8s binaries
      apt:
        name: [kubelet, kubeadm]
        state: present
        update_cache: yes
        lock_timeout: 300

    - name: 3. Join Cluster
      command: "{{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
      register: join_result

    - name: 4. Ensure Kubelet is started
      systemd:
        name: kubelet
        state: started
        enabled: yes
